// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5aDspOQQkZXQwpW-tEsYsfuxyip5JJGI',
    appId: '1:40453553422:web:0c3cfaad0f3cf8736deb5f',
    messagingSenderId: '40453553422',
    projectId: 'fir-flutter-codelab-ed718',
    authDomain: 'fir-flutter-codelab-ed718.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ed718.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg6NT6-ioIGtJI-GC8BJSsx835d9odtcU',
    appId: '1:40453553422:android:9ed4d8e1a092f3cc6deb5f',
    messagingSenderId: '40453553422',
    projectId: 'fir-flutter-codelab-ed718',
    storageBucket: 'fir-flutter-codelab-ed718.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrEfBHoMAcAZiJ7zwipGhJzSyO6oEITws',
    appId: '1:40453553422:ios:2a99f96deab083276deb5f',
    messagingSenderId: '40453553422',
    projectId: 'fir-flutter-codelab-ed718',
    storageBucket: 'fir-flutter-codelab-ed718.appspot.com',
    iosClientId: '40453553422-drh7kfdi4lr3urghl009e3u2cr248pv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.try1',
  );
}
